# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_contract.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ml_contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ml_contract.proto\x12\x0bml_paradigm\")\n\tDataPoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\"M\n\x11PredictionRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12$\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x16.ml_paradigm.DataPoint\"i\n\x12PredictionResponse\x12\x13\n\x0bprobability\x18\x01 \x01(\x02\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x1a\n\x12processing_time_ns\x18\x03 \x01(\x03\x12\x0e\n\x06status\x18\x04 \x01(\t2Y\n\x0bMLPredictor\x12J\n\x07Predict\x12\x1e.ml_paradigm.PredictionRequest\x1a\x1f.ml_paradigm.PredictionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAPOINT']._serialized_start=34
  _globals['_DATAPOINT']._serialized_end=75
  _globals['_PREDICTIONREQUEST']._serialized_start=77
  _globals['_PREDICTIONREQUEST']._serialized_end=154
  _globals['_PREDICTIONRESPONSE']._serialized_start=156
  _globals['_PREDICTIONRESPONSE']._serialized_end=261
  _globals['_MLPREDICTOR']._serialized_start=263
  _globals['_MLPREDICTOR']._serialized_end=352
# @@protoc_insertion_point(module_scope)
