// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ml_contract.proto
// Protobuf C++ Version: 7.35.0

#ifndef ml_5fcontract_2eproto_2epb_2eh
#define ml_5fcontract_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ml_5fcontract_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ml_5fcontract_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ml_5fcontract_2eproto;
}  // extern "C"
namespace ml_paradigm {
class DataPoint;
struct DataPointGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern DataPointGlobalsTypeInternal DataPoint_globals_;
extern const ::google::protobuf::internal::ClassDataFull DataPoint_class_data_;
#else
extern const DataPointGlobalsTypeInternal DataPoint_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PredictionRequest;
struct PredictionRequestGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PredictionRequestGlobalsTypeInternal PredictionRequest_globals_;
extern const ::google::protobuf::internal::ClassDataFull PredictionRequest_class_data_;
#else
extern const PredictionRequestGlobalsTypeInternal PredictionRequest_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PredictionResponse;
struct PredictionResponseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PredictionResponseGlobalsTypeInternal PredictionResponse_globals_;
extern const ::google::protobuf::internal::ClassDataFull PredictionResponse_class_data_;
#else
extern const PredictionResponseGlobalsTypeInternal PredictionResponse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class TrainRequest;
struct TrainRequestGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern TrainRequestGlobalsTypeInternal TrainRequest_globals_;
extern const ::google::protobuf::internal::ClassDataFull TrainRequest_class_data_;
#else
extern const TrainRequestGlobalsTypeInternal TrainRequest_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class TrainResponse;
struct TrainResponseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern TrainResponseGlobalsTypeInternal TrainResponse_globals_;
extern const ::google::protobuf::internal::ClassDataFull TrainResponse_class_data_;
#else
extern const TrainResponseGlobalsTypeInternal TrainResponse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace ml_paradigm
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ml_paradigm {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED TrainResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ml_paradigm.TrainResponse) */ {
 public:
  inline TrainResponse() : TrainResponse(nullptr) {}
  ~TrainResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrainResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrainResponse));
  }
#endif

  template <typename = void>
  explicit constexpr TrainResponse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline TrainResponse(const TrainResponse& from) : TrainResponse(nullptr, from) {}
  inline TrainResponse(TrainResponse&& from) noexcept : TrainResponse(nullptr, ::std::move(from)) {}
  inline TrainResponse& operator=(const TrainResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainResponse& operator=(TrainResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const TrainResponse& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<TrainResponse>(&TrainResponse_globals_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(TrainResponse& a, TrainResponse& b) { a.Swap(&b); }
  inline void Swap(TrainResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] TrainResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrainResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrainResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrainResponse& from) { TrainResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrainResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ml_paradigm.TrainResponse"; }

  explicit TrainResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TrainResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TrainResponse& from);
  TrainResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TrainResponse&& from) noexcept
      : TrainResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
    kFinalLossFieldNumber = 2,
  };
  // string status = 1;
  void clear_status() ;
  [[nodiscard]] const ::std::string& status() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_status(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_status();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_status();
  void set_allocated_status(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_status() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_status(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_status();

  public:
  // float final_loss = 2;
  void clear_final_loss() ;
  [[nodiscard]] float final_loss() const;
  void set_final_loss(float value);

  private:
  float _internal_final_loss() const;
  void _internal_set_final_loss(float value);

  public:
  // @@protoc_insertion_point(class_scope:ml_paradigm.TrainResponse)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 40,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TrainResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr status_;
    float final_loss_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ml_5fcontract_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PredictionResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ml_paradigm.PredictionResponse) */ {
 public:
  inline PredictionResponse() : PredictionResponse(nullptr) {}
  ~PredictionResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PredictionResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PredictionResponse));
  }
#endif

  template <typename = void>
  explicit constexpr PredictionResponse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PredictionResponse(const PredictionResponse& from) : PredictionResponse(nullptr, from) {}
  inline PredictionResponse(PredictionResponse&& from) noexcept : PredictionResponse(nullptr, ::std::move(from)) {}
  inline PredictionResponse& operator=(const PredictionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PredictionResponse& operator=(PredictionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PredictionResponse& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PredictionResponse>(&PredictionResponse_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PredictionResponse& a, PredictionResponse& b) { a.Swap(&b); }
  inline void Swap(PredictionResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PredictionResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PredictionResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PredictionResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PredictionResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PredictionResponse& from) { PredictionResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PredictionResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ml_paradigm.PredictionResponse"; }

  explicit PredictionResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PredictionResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PredictionResponse& from);
  PredictionResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PredictionResponse&& from) noexcept
      : PredictionResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 4,
    kProbabilityFieldNumber = 1,
    kConfidenceFieldNumber = 2,
    kProcessingTimeNsFieldNumber = 3,
  };
  // string status = 4;
  void clear_status() ;
  [[nodiscard]] const ::std::string& status() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_status(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_status();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_status();
  void set_allocated_status(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_status() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_status(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_status();

  public:
  // float probability = 1;
  void clear_probability() ;
  [[nodiscard]] float probability() const;
  void set_probability(float value);

  private:
  float _internal_probability() const;
  void _internal_set_probability(float value);

  public:
  // float confidence = 2;
  void clear_confidence() ;
  [[nodiscard]] float confidence() const;
  void set_confidence(float value);

  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);

  public:
  // int64 processing_time_ns = 3;
  void clear_processing_time_ns() ;
  [[nodiscard]] ::int64_t processing_time_ns() const;
  void set_processing_time_ns(::int64_t value);

  private:
  ::int64_t _internal_processing_time_ns() const;
  void _internal_set_processing_time_ns(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:ml_paradigm.PredictionResponse)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 4,
                          0, 45,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PredictionResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr status_;
    float probability_;
    float confidence_;
    ::int64_t processing_time_ns_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ml_5fcontract_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED DataPoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ml_paradigm.DataPoint) */ {
 public:
  inline DataPoint() : DataPoint(nullptr) {}
  ~DataPoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DataPoint* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DataPoint));
  }
#endif

  template <typename = void>
  explicit constexpr DataPoint(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline DataPoint(const DataPoint& from) : DataPoint(nullptr, from) {}
  inline DataPoint(DataPoint&& from) noexcept : DataPoint(nullptr, ::std::move(from)) {}
  inline DataPoint& operator=(const DataPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataPoint& operator=(DataPoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const DataPoint& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<DataPoint>(&DataPoint_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DataPoint& a, DataPoint& b) { a.Swap(&b); }
  inline void Swap(DataPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] DataPoint* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DataPoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DataPoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DataPoint& from) { DataPoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DataPoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ml_paradigm.DataPoint"; }

  explicit DataPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DataPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DataPoint& from);
  DataPoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DataPoint&& from) noexcept
      : DataPoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFeaturesFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated float features = 2;
  [[nodiscard]] int features_size()
      const;
  private:
  int _internal_features_size() const;

  public:
  void clear_features() ;
  [[nodiscard]] float features(int index) const;
  void set_features(int index, float value);
  void add_features(float value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<float>& features()
      const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_features();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_features() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_features();

  public:
  // int32 id = 1;
  void clear_id() ;
  [[nodiscard]] ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ml_paradigm.DataPoint)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DataPoint& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> features_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ml_5fcontract_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED TrainRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ml_paradigm.TrainRequest) */ {
 public:
  inline TrainRequest() : TrainRequest(nullptr) {}
  ~TrainRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrainRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrainRequest));
  }
#endif

  template <typename = void>
  explicit constexpr TrainRequest(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline TrainRequest(const TrainRequest& from) : TrainRequest(nullptr, from) {}
  inline TrainRequest(TrainRequest&& from) noexcept : TrainRequest(nullptr, ::std::move(from)) {}
  inline TrainRequest& operator=(const TrainRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainRequest& operator=(TrainRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const TrainRequest& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<TrainRequest>(&TrainRequest_globals_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(TrainRequest& a, TrainRequest& b) { a.Swap(&b); }
  inline void Swap(TrainRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] TrainRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrainRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrainRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrainRequest& from) { TrainRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrainRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ml_paradigm.TrainRequest"; }

  explicit TrainRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TrainRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TrainRequest& from);
  TrainRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TrainRequest&& from) noexcept
      : TrainRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBatchFieldNumber = 1,
    kLabelsFieldNumber = 2,
    kLearningRateFieldNumber = 3,
    kEpochFieldNumber = 4,
  };
  // repeated .ml_paradigm.DataPoint batch = 1;
  [[nodiscard]] int batch_size()
      const;
  private:
  int _internal_batch_size() const;

  public:
  void clear_batch() ;
  [[nodiscard]] const ::ml_paradigm::DataPoint& batch(int index) const;
  [[nodiscard]] ::ml_paradigm::DataPoint* PROTOBUF_NONNULL mutable_batch(int index);
  ::ml_paradigm::DataPoint* PROTOBUF_NONNULL add_batch();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::ml_paradigm::DataPoint>&
  batch() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::ml_paradigm::DataPoint>* PROTOBUF_NONNULL
  mutable_batch();

  private:
  const ::google::protobuf::RepeatedPtrField<::ml_paradigm::DataPoint>& _internal_batch() const;
  ::google::protobuf::RepeatedPtrField<::ml_paradigm::DataPoint>* PROTOBUF_NONNULL _internal_mutable_batch();

  public:
  // repeated int32 labels = 2;
  [[nodiscard]] int labels_size()
      const;
  private:
  int _internal_labels_size() const;

  public:
  void clear_labels() ;
  [[nodiscard]] ::int32_t labels(int index) const;
  void set_labels(int index, ::int32_t value);
  void add_labels(::int32_t value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<::int32_t>& labels()
      const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_labels();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_labels() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_labels();

  public:
  // float learning_rate = 3;
  void clear_learning_rate() ;
  [[nodiscard]] float learning_rate() const;
  void set_learning_rate(float value);

  private:
  float _internal_learning_rate() const;
  void _internal_set_learning_rate(float value);

  public:
  // int32 epoch = 4;
  void clear_epoch() ;
  [[nodiscard]] ::int32_t epoch() const;
  void set_epoch(::int32_t value);

  private:
  ::int32_t _internal_epoch() const;
  void _internal_set_epoch(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ml_paradigm.TrainRequest)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 4,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TrainRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::ml_paradigm::DataPoint > batch_;
    ::google::protobuf::RepeatedField<::int32_t> labels_;
    ::google::protobuf::internal::CachedSize _labels_cached_byte_size_;
    float learning_rate_;
    ::int32_t epoch_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ml_5fcontract_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PredictionRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ml_paradigm.PredictionRequest) */ {
 public:
  inline PredictionRequest() : PredictionRequest(nullptr) {}
  ~PredictionRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PredictionRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PredictionRequest));
  }
#endif

  template <typename = void>
  explicit constexpr PredictionRequest(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PredictionRequest(const PredictionRequest& from) : PredictionRequest(nullptr, from) {}
  inline PredictionRequest(PredictionRequest&& from) noexcept : PredictionRequest(nullptr, ::std::move(from)) {}
  inline PredictionRequest& operator=(const PredictionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PredictionRequest& operator=(PredictionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PredictionRequest& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PredictionRequest>(&PredictionRequest_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PredictionRequest& a, PredictionRequest& b) { a.Swap(&b); }
  inline void Swap(PredictionRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PredictionRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PredictionRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PredictionRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PredictionRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PredictionRequest& from) { PredictionRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PredictionRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ml_paradigm.PredictionRequest"; }

  explicit PredictionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PredictionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PredictionRequest& from);
  PredictionRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PredictionRequest&& from) noexcept
      : PredictionRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModelTypeFieldNumber = 1,
    kDataFieldNumber = 2,
  };
  // string model_type = 1;
  void clear_model_type() ;
  [[nodiscard]] const ::std::string& model_type() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_model_type(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_model_type();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_model_type();
  void set_allocated_model_type(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_model_type() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_model_type(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_model_type();

  public:
  // .ml_paradigm.DataPoint data = 2;
  [[nodiscard]] bool has_data()
      const;
  void clear_data() ;
  [[nodiscard]] const ::ml_paradigm::DataPoint& data() const;
  [[nodiscard]] ::ml_paradigm::DataPoint* PROTOBUF_NULLABLE release_data();
  ::ml_paradigm::DataPoint* PROTOBUF_NONNULL mutable_data();
  void set_allocated_data(::ml_paradigm::DataPoint* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_data(::ml_paradigm::DataPoint* PROTOBUF_NULLABLE value);
  ::ml_paradigm::DataPoint* PROTOBUF_NULLABLE unsafe_arena_release_data();

  private:
  const ::ml_paradigm::DataPoint& _internal_data() const;
  ::ml_paradigm::DataPoint* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:ml_paradigm.PredictionRequest)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          1, 48,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PredictionRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr model_type_;
    ::ml_paradigm::DataPoint* PROTOBUF_NULLABLE data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ml_5fcontract_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DataPoint

// int32 id = 1;
inline void DataPoint::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int32_t DataPoint::id() const {
  // @@protoc_insertion_point(field_get:ml_paradigm.DataPoint.id)
  return _internal_id();
}
inline void DataPoint::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:ml_paradigm.DataPoint.id)
}
inline ::int32_t DataPoint::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void DataPoint::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// repeated float features = 2;
inline int DataPoint::_internal_features_size() const {
  return _internal_features().size();
}
inline int DataPoint::features_size() const {
  return _internal_features_size();
}
inline void DataPoint::clear_features() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.features_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline float DataPoint::features(int index) const {
  // @@protoc_insertion_point(field_get:ml_paradigm.DataPoint.features)
  return _internal_features().Get(index);
}
inline void DataPoint::set_features(int index, float value) {
  _internal_mutable_features()->Set(index, value);
  // @@protoc_insertion_point(field_set:ml_paradigm.DataPoint.features)
}
inline void DataPoint::add_features(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_features()
      ->InternalAddWithArena<const ::google::protobuf::MessageLite*>(
          internal_visibility(), this, value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:ml_paradigm.DataPoint.features)
}
inline const ::google::protobuf::RepeatedField<float>& DataPoint::features() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ml_paradigm.DataPoint.features)
  return _internal_features();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL DataPoint::mutable_features()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:ml_paradigm.DataPoint.features)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_features();
}
inline const ::google::protobuf::RepeatedField<float>&
DataPoint::_internal_features() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.features_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
DataPoint::_internal_mutable_features() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.features_;
}

// -------------------------------------------------------------------

// PredictionRequest

// string model_type = 1;
inline void PredictionRequest::clear_model_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_type_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& PredictionRequest::model_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ml_paradigm.PredictionRequest.model_type)
  return _internal_model_type();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PredictionRequest::set_model_type(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.model_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ml_paradigm.PredictionRequest.model_type)
}
inline ::std::string* PROTOBUF_NONNULL PredictionRequest::mutable_model_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_model_type();
  // @@protoc_insertion_point(field_mutable:ml_paradigm.PredictionRequest.model_type)
  return _s;
}
inline const ::std::string& PredictionRequest::_internal_model_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.model_type_.Get();
}
inline void PredictionRequest::_internal_set_model_type(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_type_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PredictionRequest::_internal_mutable_model_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.model_type_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PredictionRequest::release_model_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ml_paradigm.PredictionRequest.model_type)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.model_type_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.model_type_.Set("", GetArena());
  }
  return released;
}
inline void PredictionRequest::set_allocated_model_type(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.model_type_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.model_type_.IsDefault()) {
    _impl_.model_type_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ml_paradigm.PredictionRequest.model_type)
}

// .ml_paradigm.DataPoint data = 2;
inline bool PredictionRequest::has_data() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.data_ != nullptr);
  return value;
}
inline void PredictionRequest::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.data_ != nullptr) _impl_.data_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::ml_paradigm::DataPoint& PredictionRequest::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::ml_paradigm::DataPoint* p = _impl_.data_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::ml_paradigm::DataPoint>(&::ml_paradigm::DataPoint_globals_);
}
inline const ::ml_paradigm::DataPoint& PredictionRequest::data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ml_paradigm.PredictionRequest.data)
  return _internal_data();
}
inline void PredictionRequest::unsafe_arena_set_allocated_data(
    ::ml_paradigm::DataPoint* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.data_);
  }
  _impl_.data_ = reinterpret_cast<::ml_paradigm::DataPoint*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ml_paradigm.PredictionRequest.data)
}
inline ::ml_paradigm::DataPoint* PROTOBUF_NULLABLE PredictionRequest::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::ml_paradigm::DataPoint* released = _impl_.data_;
  _impl_.data_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::ml_paradigm::DataPoint* PROTOBUF_NULLABLE PredictionRequest::unsafe_arena_release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ml_paradigm.PredictionRequest.data)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::ml_paradigm::DataPoint* temp = _impl_.data_;
  _impl_.data_ = nullptr;
  return temp;
}
inline ::ml_paradigm::DataPoint* PROTOBUF_NONNULL PredictionRequest::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.data_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::ml_paradigm::DataPoint>(GetArena());
    _impl_.data_ = reinterpret_cast<::ml_paradigm::DataPoint*>(p);
  }
  return _impl_.data_;
}
inline ::ml_paradigm::DataPoint* PROTOBUF_NONNULL PredictionRequest::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::ml_paradigm::DataPoint* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:ml_paradigm.PredictionRequest.data)
  return _msg;
}
inline void PredictionRequest::set_allocated_data(::ml_paradigm::DataPoint* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.data_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.data_ = reinterpret_cast<::ml_paradigm::DataPoint*>(value);
  // @@protoc_insertion_point(field_set_allocated:ml_paradigm.PredictionRequest.data)
}

// -------------------------------------------------------------------

// PredictionResponse

// float probability = 1;
inline void PredictionResponse::clear_probability() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.probability_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline float PredictionResponse::probability() const {
  // @@protoc_insertion_point(field_get:ml_paradigm.PredictionResponse.probability)
  return _internal_probability();
}
inline void PredictionResponse::set_probability(float value) {
  _internal_set_probability(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:ml_paradigm.PredictionResponse.probability)
}
inline float PredictionResponse::_internal_probability() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.probability_;
}
inline void PredictionResponse::_internal_set_probability(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.probability_ = value;
}

// float confidence = 2;
inline void PredictionResponse::clear_confidence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.confidence_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline float PredictionResponse::confidence() const {
  // @@protoc_insertion_point(field_get:ml_paradigm.PredictionResponse.confidence)
  return _internal_confidence();
}
inline void PredictionResponse::set_confidence(float value) {
  _internal_set_confidence(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:ml_paradigm.PredictionResponse.confidence)
}
inline float PredictionResponse::_internal_confidence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.confidence_;
}
inline void PredictionResponse::_internal_set_confidence(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.confidence_ = value;
}

// int64 processing_time_ns = 3;
inline void PredictionResponse::clear_processing_time_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processing_time_ns_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int64_t PredictionResponse::processing_time_ns() const {
  // @@protoc_insertion_point(field_get:ml_paradigm.PredictionResponse.processing_time_ns)
  return _internal_processing_time_ns();
}
inline void PredictionResponse::set_processing_time_ns(::int64_t value) {
  _internal_set_processing_time_ns(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:ml_paradigm.PredictionResponse.processing_time_ns)
}
inline ::int64_t PredictionResponse::_internal_processing_time_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.processing_time_ns_;
}
inline void PredictionResponse::_internal_set_processing_time_ns(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processing_time_ns_ = value;
}

// string status = 4;
inline void PredictionResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& PredictionResponse::status() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ml_paradigm.PredictionResponse.status)
  return _internal_status();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PredictionResponse::set_status(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.status_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ml_paradigm.PredictionResponse.status)
}
inline ::std::string* PROTOBUF_NONNULL PredictionResponse::mutable_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:ml_paradigm.PredictionResponse.status)
  return _s;
}
inline const ::std::string& PredictionResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_.Get();
}
inline void PredictionResponse::_internal_set_status(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PredictionResponse::_internal_mutable_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.status_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PredictionResponse::release_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ml_paradigm.PredictionResponse.status)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.status_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.status_.Set("", GetArena());
  }
  return released;
}
inline void PredictionResponse::set_allocated_status(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.status_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ml_paradigm.PredictionResponse.status)
}

// -------------------------------------------------------------------

// TrainRequest

// repeated .ml_paradigm.DataPoint batch = 1;
inline int TrainRequest::_internal_batch_size() const {
  return _internal_batch().size();
}
inline int TrainRequest::batch_size() const {
  return _internal_batch_size();
}
inline void TrainRequest::clear_batch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::ml_paradigm::DataPoint& TrainRequest::batch(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ml_paradigm.TrainRequest.batch)
  return _internal_batch().Get(index);
}
inline ::ml_paradigm::DataPoint* PROTOBUF_NONNULL TrainRequest::mutable_batch(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ml_paradigm.TrainRequest.batch)
  return _internal_mutable_batch()->Mutable(index);
}
inline ::ml_paradigm::DataPoint* PROTOBUF_NONNULL TrainRequest::add_batch()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::ml_paradigm::DataPoint* _add =
      _internal_mutable_batch()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:ml_paradigm.TrainRequest.batch)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::ml_paradigm::DataPoint>& TrainRequest::batch() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ml_paradigm.TrainRequest.batch)
  return _internal_batch();
}
inline ::google::protobuf::RepeatedPtrField<::ml_paradigm::DataPoint>* PROTOBUF_NONNULL
TrainRequest::mutable_batch() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:ml_paradigm.TrainRequest.batch)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_batch();
}
inline const ::google::protobuf::RepeatedPtrField<::ml_paradigm::DataPoint>&
TrainRequest::_internal_batch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.batch_;
}
inline ::google::protobuf::RepeatedPtrField<::ml_paradigm::DataPoint>* PROTOBUF_NONNULL
TrainRequest::_internal_mutable_batch() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.batch_;
}

// repeated int32 labels = 2;
inline int TrainRequest::_internal_labels_size() const {
  return _internal_labels().size();
}
inline int TrainRequest::labels_size() const {
  return _internal_labels_size();
}
inline void TrainRequest::clear_labels() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.labels_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int32_t TrainRequest::labels(int index) const {
  // @@protoc_insertion_point(field_get:ml_paradigm.TrainRequest.labels)
  return _internal_labels().Get(index);
}
inline void TrainRequest::set_labels(int index, ::int32_t value) {
  _internal_mutable_labels()->Set(index, value);
  // @@protoc_insertion_point(field_set:ml_paradigm.TrainRequest.labels)
}
inline void TrainRequest::add_labels(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_labels()
      ->InternalAddWithArena<const ::google::protobuf::MessageLite*>(
          internal_visibility(), this, value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:ml_paradigm.TrainRequest.labels)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& TrainRequest::labels() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ml_paradigm.TrainRequest.labels)
  return _internal_labels();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL TrainRequest::mutable_labels()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:ml_paradigm.TrainRequest.labels)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_labels();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
TrainRequest::_internal_labels() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.labels_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
TrainRequest::_internal_mutable_labels() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.labels_;
}

// float learning_rate = 3;
inline void TrainRequest::clear_learning_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.learning_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline float TrainRequest::learning_rate() const {
  // @@protoc_insertion_point(field_get:ml_paradigm.TrainRequest.learning_rate)
  return _internal_learning_rate();
}
inline void TrainRequest::set_learning_rate(float value) {
  _internal_set_learning_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:ml_paradigm.TrainRequest.learning_rate)
}
inline float TrainRequest::_internal_learning_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.learning_rate_;
}
inline void TrainRequest::_internal_set_learning_rate(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.learning_rate_ = value;
}

// int32 epoch = 4;
inline void TrainRequest::clear_epoch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.epoch_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int32_t TrainRequest::epoch() const {
  // @@protoc_insertion_point(field_get:ml_paradigm.TrainRequest.epoch)
  return _internal_epoch();
}
inline void TrainRequest::set_epoch(::int32_t value) {
  _internal_set_epoch(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:ml_paradigm.TrainRequest.epoch)
}
inline ::int32_t TrainRequest::_internal_epoch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.epoch_;
}
inline void TrainRequest::_internal_set_epoch(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.epoch_ = value;
}

// -------------------------------------------------------------------

// TrainResponse

// string status = 1;
inline void TrainResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& TrainResponse::status() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ml_paradigm.TrainResponse.status)
  return _internal_status();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TrainResponse::set_status(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.status_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ml_paradigm.TrainResponse.status)
}
inline ::std::string* PROTOBUF_NONNULL TrainResponse::mutable_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:ml_paradigm.TrainResponse.status)
  return _s;
}
inline const ::std::string& TrainResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_.Get();
}
inline void TrainResponse::_internal_set_status(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TrainResponse::_internal_mutable_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.status_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TrainResponse::release_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ml_paradigm.TrainResponse.status)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.status_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.status_.Set("", GetArena());
  }
  return released;
}
inline void TrainResponse::set_allocated_status(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.status_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ml_paradigm.TrainResponse.status)
}

// float final_loss = 2;
inline void TrainResponse::clear_final_loss() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.final_loss_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline float TrainResponse::final_loss() const {
  // @@protoc_insertion_point(field_get:ml_paradigm.TrainResponse.final_loss)
  return _internal_final_loss();
}
inline void TrainResponse::set_final_loss(float value) {
  _internal_set_final_loss(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:ml_paradigm.TrainResponse.final_loss)
}
inline float TrainResponse::_internal_final_loss() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.final_loss_;
}
inline void TrainResponse::_internal_set_final_loss(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.final_loss_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ml_paradigm


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // ml_5fcontract_2eproto_2epb_2eh
