// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ml_contract.proto
// Protobuf C++ Version: 6.33.5

#include "ml_contract.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ml_paradigm {

inline constexpr PredictionResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        probability_{0},
        confidence_{0},
        processing_time_ns_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR PredictionResponse::PredictionResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PredictionResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PredictionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PredictionResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PredictionResponseDefaultTypeInternal() {}
  union {
    PredictionResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PredictionResponseDefaultTypeInternal _PredictionResponse_default_instance_;

inline constexpr DataPoint::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        features_{},
        id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DataPoint::DataPoint(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DataPoint_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DataPointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataPointDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataPointDefaultTypeInternal() {}
  union {
    DataPoint _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataPointDefaultTypeInternal _DataPoint_default_instance_;

inline constexpr PredictionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        model_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR PredictionRequest::PredictionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PredictionRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PredictionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PredictionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PredictionRequestDefaultTypeInternal() {}
  union {
    PredictionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PredictionRequestDefaultTypeInternal _PredictionRequest_default_instance_;
}  // namespace ml_paradigm
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_ml_5fcontract_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_ml_5fcontract_2eproto = nullptr;
const ::uint32_t
    TableStruct_ml_5fcontract_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::DataPoint, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::DataPoint, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::DataPoint, _impl_.features_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::PredictionRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::PredictionRequest, _impl_.model_type_),
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::PredictionRequest, _impl_.data_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::PredictionResponse, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::PredictionResponse, _impl_.probability_),
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::PredictionResponse, _impl_.confidence_),
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::PredictionResponse, _impl_.processing_time_ns_),
        PROTOBUF_FIELD_OFFSET(::ml_paradigm::PredictionResponse, _impl_.status_),
        1,
        2,
        3,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::ml_paradigm::DataPoint)},
        {7, sizeof(::ml_paradigm::PredictionRequest)},
        {14, sizeof(::ml_paradigm::PredictionResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::ml_paradigm::_DataPoint_default_instance_._instance,
    &::ml_paradigm::_PredictionRequest_default_instance_._instance,
    &::ml_paradigm::_PredictionResponse_default_instance_._instance,
};
const char descriptor_table_protodef_ml_5fcontract_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021ml_contract.proto\022\013ml_paradigm\")\n\tData"
    "Point\022\n\n\002id\030\001 \001(\005\022\020\n\010features\030\002 \003(\002\"M\n\021P"
    "redictionRequest\022\022\n\nmodel_type\030\001 \001(\t\022$\n\004"
    "data\030\002 \001(\0132\026.ml_paradigm.DataPoint\"i\n\022Pr"
    "edictionResponse\022\023\n\013probability\030\001 \001(\002\022\022\n"
    "\nconfidence\030\002 \001(\002\022\032\n\022processing_time_ns\030"
    "\003 \001(\003\022\016\n\006status\030\004 \001(\t2Y\n\013MLPredictor\022J\n\007"
    "Predict\022\036.ml_paradigm.PredictionRequest\032"
    "\037.ml_paradigm.PredictionResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_ml_5fcontract_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ml_5fcontract_2eproto = {
    false,
    false,
    360,
    descriptor_table_protodef_ml_5fcontract_2eproto,
    "ml_contract.proto",
    &descriptor_table_ml_5fcontract_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_ml_5fcontract_2eproto::offsets,
    file_level_enum_descriptors_ml_5fcontract_2eproto,
    file_level_service_descriptors_ml_5fcontract_2eproto,
};
namespace ml_paradigm {
// ===================================================================

class DataPoint::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<DataPoint>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DataPoint, _impl_._has_bits_);
};

DataPoint::DataPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DataPoint_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ml_paradigm.DataPoint)
}
PROTOBUF_NDEBUG_INLINE DataPoint::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ml_paradigm::DataPoint& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        features_{visibility, arena, from.features_} {}

DataPoint::DataPoint(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DataPoint& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DataPoint_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DataPoint* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:ml_paradigm.DataPoint)
}
PROTOBUF_NDEBUG_INLINE DataPoint::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        features_{visibility, arena} {}

inline void DataPoint::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
DataPoint::~DataPoint() {
  // @@protoc_insertion_point(destructor:ml_paradigm.DataPoint)
  SharedDtor(*this);
}
inline void DataPoint::SharedDtor(MessageLite& self) {
  DataPoint& this_ = static_cast<DataPoint&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DataPoint::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DataPoint(arena);
}
constexpr auto DataPoint::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DataPoint, _impl_.features_) +
          decltype(DataPoint::_impl_.features_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(DataPoint), alignof(DataPoint), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DataPoint::PlacementNew_,
                                 sizeof(DataPoint),
                                 alignof(DataPoint));
  }
}
constexpr auto DataPoint::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DataPoint_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DataPoint::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DataPoint>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DataPoint::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DataPoint>(), &DataPoint::ByteSizeLong,
              &DataPoint::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DataPoint, _impl_._cached_size_),
          false,
      },
      &DataPoint::kDescriptorMethods,
      &descriptor_table_ml_5fcontract_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull DataPoint_class_data_ =
        DataPoint::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DataPoint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DataPoint_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DataPoint_class_data_.tc_table);
  return DataPoint_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
DataPoint::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DataPoint, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    DataPoint_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ml_paradigm::DataPoint>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float features = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(DataPoint, _impl_.features_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DataPoint, _impl_.id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(DataPoint, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(DataPoint, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated float features = 2;
    {PROTOBUF_FIELD_OFFSET(DataPoint, _impl_.features_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void DataPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:ml_paradigm.DataPoint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.features_.Clear();
  }
  _impl_.id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DataPoint::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DataPoint& this_ = static_cast<const DataPoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DataPoint::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DataPoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ml_paradigm.DataPoint)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // repeated float features = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    if (this_._internal_features_size() > 0) {
      target = stream->WriteFixedPacked(2, this_._internal_features(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ml_paradigm.DataPoint)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DataPoint::ByteSizeLong(const MessageLite& base) {
  const DataPoint& this_ = static_cast<const DataPoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DataPoint::ByteSizeLong() const {
  const DataPoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ml_paradigm.DataPoint)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated float features = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_features_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DataPoint::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<DataPoint*>(&to_msg);
  auto& from = static_cast<const DataPoint&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:ml_paradigm.DataPoint)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_features()->MergeFrom(from._internal_features());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void DataPoint::CopyFrom(const DataPoint& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ml_paradigm.DataPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DataPoint::InternalSwap(DataPoint* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.features_.InternalSwap(&other->_impl_.features_);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata DataPoint::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PredictionRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PredictionRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PredictionRequest, _impl_._has_bits_);
};

PredictionRequest::PredictionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PredictionRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ml_paradigm.PredictionRequest)
}
PROTOBUF_NDEBUG_INLINE PredictionRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ml_paradigm::PredictionRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        model_type_(arena, from.model_type_) {}

PredictionRequest::PredictionRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PredictionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PredictionRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PredictionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.data_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.data_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:ml_paradigm.PredictionRequest)
}
PROTOBUF_NDEBUG_INLINE PredictionRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        model_type_(arena) {}

inline void PredictionRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.data_ = {};
}
PredictionRequest::~PredictionRequest() {
  // @@protoc_insertion_point(destructor:ml_paradigm.PredictionRequest)
  SharedDtor(*this);
}
inline void PredictionRequest::SharedDtor(MessageLite& self) {
  PredictionRequest& this_ = static_cast<PredictionRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.model_type_.Destroy();
  delete this_._impl_.data_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PredictionRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PredictionRequest(arena);
}
constexpr auto PredictionRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PredictionRequest),
                                            alignof(PredictionRequest));
}
constexpr auto PredictionRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PredictionRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PredictionRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PredictionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PredictionRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PredictionRequest>(), &PredictionRequest::ByteSizeLong,
              &PredictionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PredictionRequest, _impl_._cached_size_),
          false,
      },
      &PredictionRequest::kDescriptorMethods,
      &descriptor_table_ml_5fcontract_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PredictionRequest_class_data_ =
        PredictionRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PredictionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PredictionRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PredictionRequest_class_data_.tc_table);
  return PredictionRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 48, 2>
PredictionRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PredictionRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PredictionRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ml_paradigm::PredictionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .ml_paradigm.DataPoint data = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(PredictionRequest, _impl_.data_)}},
    // string model_type = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PredictionRequest, _impl_.model_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string model_type = 1;
    {PROTOBUF_FIELD_OFFSET(PredictionRequest, _impl_.model_type_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .ml_paradigm.DataPoint data = 2;
    {PROTOBUF_FIELD_OFFSET(PredictionRequest, _impl_.data_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::ml_paradigm::DataPoint>()},
  }},
  {{
    "\35\12\0\0\0\0\0\0"
    "ml_paradigm.PredictionRequest"
    "model_type"
  }},
};
PROTOBUF_NOINLINE void PredictionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ml_paradigm.PredictionRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.model_type_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.data_ != nullptr);
      _impl_.data_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PredictionRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PredictionRequest& this_ = static_cast<const PredictionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PredictionRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PredictionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ml_paradigm.PredictionRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string model_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_model_type().empty()) {
      const ::std::string& _s = this_._internal_model_type();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ml_paradigm.PredictionRequest.model_type");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .ml_paradigm.DataPoint data = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.data_, this_._impl_.data_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ml_paradigm.PredictionRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PredictionRequest::ByteSizeLong(const MessageLite& base) {
  const PredictionRequest& this_ = static_cast<const PredictionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PredictionRequest::ByteSizeLong() const {
  const PredictionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ml_paradigm.PredictionRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string model_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_model_type().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_model_type());
      }
    }
    // .ml_paradigm.DataPoint data = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.data_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PredictionRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PredictionRequest*>(&to_msg);
  auto& from = static_cast<const PredictionRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:ml_paradigm.PredictionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_model_type().empty()) {
        _this->_internal_set_model_type(from._internal_model_type());
      } else {
        if (_this->_impl_.model_type_.IsDefault()) {
          _this->_internal_set_model_type("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.data_ != nullptr);
      if (_this->_impl_.data_ == nullptr) {
        _this->_impl_.data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.data_);
      } else {
        _this->_impl_.data_->MergeFrom(*from._impl_.data_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PredictionRequest::CopyFrom(const PredictionRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ml_paradigm.PredictionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PredictionRequest::InternalSwap(PredictionRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.model_type_, &other->_impl_.model_type_, arena);
  swap(_impl_.data_, other->_impl_.data_);
}

::google::protobuf::Metadata PredictionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PredictionResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PredictionResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_._has_bits_);
};

PredictionResponse::PredictionResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PredictionResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ml_paradigm.PredictionResponse)
}
PROTOBUF_NDEBUG_INLINE PredictionResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ml_paradigm::PredictionResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        status_(arena, from.status_) {}

PredictionResponse::PredictionResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PredictionResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PredictionResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PredictionResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, probability_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, probability_),
           offsetof(Impl_, processing_time_ns_) -
               offsetof(Impl_, probability_) +
               sizeof(Impl_::processing_time_ns_));

  // @@protoc_insertion_point(copy_constructor:ml_paradigm.PredictionResponse)
}
PROTOBUF_NDEBUG_INLINE PredictionResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        status_(arena) {}

inline void PredictionResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, probability_),
           0,
           offsetof(Impl_, processing_time_ns_) -
               offsetof(Impl_, probability_) +
               sizeof(Impl_::processing_time_ns_));
}
PredictionResponse::~PredictionResponse() {
  // @@protoc_insertion_point(destructor:ml_paradigm.PredictionResponse)
  SharedDtor(*this);
}
inline void PredictionResponse::SharedDtor(MessageLite& self) {
  PredictionResponse& this_ = static_cast<PredictionResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.status_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PredictionResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PredictionResponse(arena);
}
constexpr auto PredictionResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PredictionResponse),
                                            alignof(PredictionResponse));
}
constexpr auto PredictionResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PredictionResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PredictionResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PredictionResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PredictionResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PredictionResponse>(), &PredictionResponse::ByteSizeLong,
              &PredictionResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_._cached_size_),
          false,
      },
      &PredictionResponse::kDescriptorMethods,
      &descriptor_table_ml_5fcontract_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PredictionResponse_class_data_ =
        PredictionResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PredictionResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PredictionResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PredictionResponse_class_data_.tc_table);
  return PredictionResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 45, 2>
PredictionResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PredictionResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ml_paradigm::PredictionResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string status = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 0, 0,
      PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.status_)}},
    // float probability = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 1, 0,
      PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.probability_)}},
    // float confidence = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 2, 0,
      PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.confidence_)}},
    // int64 processing_time_ns = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PredictionResponse, _impl_.processing_time_ns_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.processing_time_ns_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float probability = 1;
    {PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.probability_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float confidence = 2;
    {PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.confidence_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // int64 processing_time_ns = 3;
    {PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.processing_time_ns_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // string status = 4;
    {PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.status_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\0\0\0\6\0\0\0"
    "ml_paradigm.PredictionResponse"
    "status"
  }},
};
PROTOBUF_NOINLINE void PredictionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ml_paradigm.PredictionResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.status_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000eU)) {
    ::memset(&_impl_.probability_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.processing_time_ns_) -
        reinterpret_cast<char*>(&_impl_.probability_)) + sizeof(_impl_.processing_time_ns_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PredictionResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PredictionResponse& this_ = static_cast<const PredictionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PredictionResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PredictionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ml_paradigm.PredictionResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // float probability = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_probability()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          1, this_._internal_probability(), target);
    }
  }

  // float confidence = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_confidence(), target);
    }
  }

  // int64 processing_time_ns = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_processing_time_ns() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_processing_time_ns(), target);
    }
  }

  // string status = 4;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_status().empty()) {
      const ::std::string& _s = this_._internal_status();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ml_paradigm.PredictionResponse.status");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ml_paradigm.PredictionResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PredictionResponse::ByteSizeLong(const MessageLite& base) {
  const PredictionResponse& this_ = static_cast<const PredictionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PredictionResponse::ByteSizeLong() const {
  const PredictionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ml_paradigm.PredictionResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string status = 4;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_status().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_status());
      }
    }
    // float probability = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_probability()) != 0) {
        total_size += 5;
      }
    }
    // float confidence = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
        total_size += 5;
      }
    }
    // int64 processing_time_ns = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_processing_time_ns() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_processing_time_ns());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PredictionResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PredictionResponse*>(&to_msg);
  auto& from = static_cast<const PredictionResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:ml_paradigm.PredictionResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_status().empty()) {
        _this->_internal_set_status(from._internal_status());
      } else {
        if (_this->_impl_.status_.IsDefault()) {
          _this->_internal_set_status("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_probability()) != 0) {
        _this->_impl_.probability_ = from._impl_.probability_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_confidence()) != 0) {
        _this->_impl_.confidence_ = from._impl_.confidence_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_processing_time_ns() != 0) {
        _this->_impl_.processing_time_ns_ = from._impl_.processing_time_ns_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PredictionResponse::CopyFrom(const PredictionResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ml_paradigm.PredictionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PredictionResponse::InternalSwap(PredictionResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, &other->_impl_.status_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.processing_time_ns_)
      + sizeof(PredictionResponse::_impl_.processing_time_ns_)
      - PROTOBUF_FIELD_OFFSET(PredictionResponse, _impl_.probability_)>(
          reinterpret_cast<char*>(&_impl_.probability_),
          reinterpret_cast<char*>(&other->_impl_.probability_));
}

::google::protobuf::Metadata PredictionResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ml_paradigm
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_ml_5fcontract_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
