// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ml_contract.proto

#include "ml_contract.pb.h"
#include "ml_contract.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace ml_paradigm {

static const char* MLPredictor_method_names[] = {
  "/ml_paradigm.MLPredictor/Predict",
};

std::unique_ptr< MLPredictor::Stub> MLPredictor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MLPredictor::Stub> stub(new MLPredictor::Stub(channel, options));
  return stub;
}

MLPredictor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Predict_(MLPredictor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MLPredictor::Stub::Predict(::grpc::ClientContext* context, const ::ml_paradigm::PredictionRequest& request, ::ml_paradigm::PredictionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ml_paradigm::PredictionRequest, ::ml_paradigm::PredictionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Predict_, context, request, response);
}

void MLPredictor::Stub::async::Predict(::grpc::ClientContext* context, const ::ml_paradigm::PredictionRequest* request, ::ml_paradigm::PredictionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ml_paradigm::PredictionRequest, ::ml_paradigm::PredictionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, std::move(f));
}

void MLPredictor::Stub::async::Predict(::grpc::ClientContext* context, const ::ml_paradigm::PredictionRequest* request, ::ml_paradigm::PredictionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ml_paradigm::PredictionResponse>* MLPredictor::Stub::PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::ml_paradigm::PredictionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ml_paradigm::PredictionResponse, ::ml_paradigm::PredictionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Predict_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ml_paradigm::PredictionResponse>* MLPredictor::Stub::AsyncPredictRaw(::grpc::ClientContext* context, const ::ml_paradigm::PredictionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPredictRaw(context, request, cq);
  result->StartCall();
  return result;
}

MLPredictor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MLPredictor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MLPredictor::Service, ::ml_paradigm::PredictionRequest, ::ml_paradigm::PredictionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MLPredictor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ml_paradigm::PredictionRequest* req,
             ::ml_paradigm::PredictionResponse* resp) {
               return service->Predict(ctx, req, resp);
             }, this)));
}

MLPredictor::Service::~Service() {
}

::grpc::Status MLPredictor::Service::Predict(::grpc::ServerContext* context, const ::ml_paradigm::PredictionRequest* request, ::ml_paradigm::PredictionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ml_paradigm
#include <grpcpp/ports_undef.inc>

